# Schema for the configuration files of the Display Suite module.

ds.settings:
  type: mapping
  label: 'Display Suite settings'
  mapping:
    disable:
      type: boolean
      label: 'Disable Display Suite attaching fields'
    additional_settings__active_tab:
      label: 'Active tab'
    field_template:
      type: boolean
      label: 'Uses field templates'
    ft-default:
      label: 'The default template'
    ft-kill-colon:
      type: boolean
      label: 'Kill the label colon'

ds.classes:
  type: mapping
  label: 'Display Suite classes'
  mapping:
    regions:
      label: 'Region classes'
    fields:
      label: 'Field classes'
